# Generated by Django 4.2.11 on 2024-12-08 08:49

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='blogs')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AddImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(choices=[('about', 'About Image'), ('top', 'Top Image')], max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='AddProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tittle', models.CharField(choices=[('graphic_design', 'Graphic Design'), ('development', 'Web Development'), ('web_design', 'Web Design')], max_length=200)),
                ('image', models.ImageField(upload_to='projects')),
            ],
        ),
        migrations.CreateModel(
            name='AddReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profession', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='reviews')),
                ('messange', models.TextField(max_length=1000)),
                ('rating', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='buyMeCoffee',
            fields=[
                ('id', models.CharField(default=app.models.generate_order_id, editable=False, max_length=15, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=200, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=200, null=True)),
                ('result_code', models.PositiveIntegerField(blank=True, null=True)),
                ('result_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
