# Generated by Django 4.2.11 on 2024-12-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='tittle',
            field=models.CharField(choices=[('development', 'Web Development'), ('web_design', 'Web Design'), ('graphic_design', 'Graphic Design')], max_length=200),
        ),
    ]
