# Generated by Django 4.2.11 on 2024-03-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='tittle',
            field=models.CharField(choices=[('design', 'Design'), ('development', 'Development')], max_length=200),
        ),
    ]
