# Generated by Django 4.2 on 2023-06-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addimage',
            name='tittle',
            field=models.CharField(choices=[('about', 'About Image'), ('top', 'Top Image')], max_length=200),
        ),
    ]
