# Generated by Django 4.2.11 on 2024-04-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_addimage_tittle_alter_addproject_tittle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='addimage',
            name='tittle',
            field=models.CharField(choices=[('about', 'About Image'), ('top', 'Top Image')], max_length=200),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='tittle',
            field=models.CharField(choices=[('design', 'Design'), ('development', 'Development')], max_length=200),
        ),
    ]
