# Generated by Django 4.2.11 on 2024-12-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_addproject_tittle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='tittle',
            field=models.CharField(choices=[('web_design', 'Web Design'), ('development', 'Web Development'), ('graphic_design', 'Graphic Design')], max_length=200),
        ),
        migrations.AlterField(
            model_name='buymecoffee',
            name='result_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
