# Generated by Django 4.2.11 on 2024-04-06 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_addblog_description_alter_addimage_tittle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproject',
            name='url',
        ),
        migrations.AddField(
            model_name='addreview',
            name='rating',
            field=models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
