# Generated by Django 4.2 on 2023-06-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_addproject_tittle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='tittle',
            field=models.CharField(choices=[('design', 'Design'), ('development', 'Development')], max_length=200),
        ),
    ]
