# Generated by Django 4.2.11 on 2025-01-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_addreview_is_approved_alter_addproject_tittle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='tittle',
            field=models.CharField(choices=[('graphic_design', 'Graphic Design'), ('web_design', 'Web Design'), ('development', 'Web Development')], max_length=200),
        ),
    ]
