# Generated by Django 4.2.11 on 2024-04-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_addproject_tittle_alter_addreview_messange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addimage',
            name='tittle',
            field=models.CharField(choices=[('top', 'Top Image'), ('about', 'About Image')], max_length=200),
        ),
        migrations.AlterField(
            model_name='addreview',
            name='profession',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
