# Generated by Django 4.2.11 on 2024-11-28 18:00

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_addimage_tittle_alter_addreview_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyMeCoffee',
            fields=[
                ('id', models.CharField(default=app.models.generate_order_id, editable=False, max_length=15, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=200, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MpesaCallBacks',
        ),
        migrations.DeleteModel(
            name='MpesaCalls',
        ),
        migrations.DeleteModel(
            name='MpesaPayment',
        ),
        migrations.DeleteModel(
            name='Pay',
        ),
        migrations.AlterField(
            model_name='addproject',
            name='tittle',
            field=models.CharField(choices=[('web_design', 'Web Design'), ('development', 'Web Development'), ('graphic_design', 'Graphic Design')], max_length=200),
        ),
    ]
