# Generated by Django 4.2 on 2023-06-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_addproject_tittle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='tittle',
            field=models.CharField(choices=[('development', 'Development'), ('design', 'Design')], max_length=200),
        ),
    ]
