# Generated by Django 4.2.11 on 2024-11-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_buymecoffee_delete_mpesacallbacks_delete_mpesacalls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buymecoffee',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=200),
        ),
        migrations.AlterField(
            model_name='addimage',
            name='tittle',
            field=models.CharField(choices=[('about', 'About Image'), ('top', 'Top Image')], max_length=200),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='tittle',
            field=models.CharField(choices=[('web_design', 'Web Design'), ('graphic_design', 'Graphic Design'), ('development', 'Web Development')], max_length=200),
        ),
    ]
